### ISSUE TITLE
xOperaSaaS che plugin fails after login.

### ISSUE THREAD

**Issue by cankarm** [xlab-si/radon-xopera-saas-plugin#4]
Currently, it is impossible to use xOperaSaaS plugin from Che, as it fails just after the login.

The issue can be related to the upgrade of xOpera/xOperaSaaS and related changes of API (credentials/secrets).

**Comment by sstanovnik** [comment]
Cause: backwards-incompatible API change prevented the Plugin from operating correctly. An invalid URL was used to validate the authentication status of a user, upon which an unexpected error was thrown. This halted execution and produced a generic error message.

Resolution: This has been resolved by the latest version of the xopera-saas Che plugin, which includes the latest API definitions.

Steps for prevention of similar issues: None, as the API of xopera-saas has not yet stabilised.
